
development:
  adapter : postgresql
  database : Annette
  pool : 5
  timeout : 5000

test:  
  adapter : postgresql
  database : Annette
  pool : 5
  timeout : 5000

production:
  adapter : postgresql
  database : Annette
  pool : 5
  timeout : 5000  